### ISSUE TITLE
Is there a way to configure a step to have two parallel condition for running a step?

### ISSUE THREAD

**Issue by Emmawaterman** [meltwater/drone-convert-pathschanged#17]
Is there a way to configure drone yaml with your plugin so that it can run with master change or one specific file change? Which means either case satisfies it will run.

**Comment by hikerspath** [comment]
Conditionals are always usable in any pipeline step.  These are capable of filtering each step by branch, event, reference, status, and more:

* https://docs.drone.io/pipeline/docker/syntax/steps/#conditions

However, you also asked about being able to accomplish the same through specific files being altered.  Though a bit less well known we have a plugin that is able to accomplish just that.

* https://github.com/meltwater/drone-convert-pathschanged

Let me know if these answer your question or not, I will keep this issue open for comment for next couple of days.
