### ISSUE TITLE
Only works with GitHub?

### ISSUE THREAD

**Issue by rafi** [meltwater/drone-convert-pathschanged#19]
Wondering about Gitea support.

**Comment by jimsheldon** [comment]
Hello @rafi, thank you for the interest!

At the moment GitHub is our only use case.  We would certainly be open to a pull request to add Gitea support.  Is that something you would like to work on?

**Comment by rafi** [comment]
@jimsheldon i need this feature so I'll eventually do it one way or another, i'm currently quite busy though. Apparently the first thing is decoupling GitHub's api from `plugin/get.go` and allow a selection of providers to be developed down the road.

**Comment by jimsheldon** [comment]
Ok, perhaps if this projects gains traction we will get help with adding other providers.  For now, I will close this out.  Feel free to share any improvements you make in the future.
