### ISSUE TITLE
How to handle releases with multiple commits?

### ISSUE THREAD

**Issue by RayBB** [meltwater/drone-convert-pathschanged#25]
Hello,

It appears that this project only looks at the most recent commit when looking for changes in files.

I have run into a small issue and was wondering if you have any ideas on how to work around it.

We do a production deploy whenever the master branch is tagged. Most of the time that happens after we push to master. However, sometimes there may be multiple commits pushed to master before releasing. If the most recent commit doesn't touch the same paths that the previous commits touched then the step won't be triggered on release. 

A simple example is when drone is setup to only deploy the frontend when the `frontend/` folder changes. I push changes to that folder to master. Then right after I realize I forgot to update the readme so I push that to master. Now, when I tag a release the plugin won't realize that there was a change to `frontend/` since the last release and it won't deploy the frontend.

Is there any way this plugin can look back at all the commits since the last release when checking the paths?

Thanks so much for your work on this plugin!

**Comment by hikerspath** [comment]
The difference between tags and branches are that a branch always points to the top of a development line and will change when a new commit is pushed, a tag will not. Tags designate a point in time and are un-changing.
