### ISSUE TITLE
Not compatible with drone-yaml

### ISSUE THREAD

**Issue by captncraig** [meltwater/drone-convert-pathschanged#26]
I have a bit of an odd workflow perhaps. I am using drone jsonnet to generate my final yml output. That plugin runs all of the final yaml through a parse and pretty-print phase. So even if I input jsonnet like:

```
trigger+: {
    paths+: {
      include: ["abc"],
    },
  },
```

 `drone jsonnet` will output something like:

```
trigger:
  paths:
  - abc
```

Rather than have Include and Exclude fields, they assume a single string or list of strings is an Include. They have [custom parsing](https://github.com/drone/drone-yaml/blob/6f4d6dfb39e40f92d31cb113f2cdcb19387d163b/yaml/cond.go#L78) and [printing](https://github.com/drone/drone-yaml/blob/master/yaml/pretty/pipeline.go#L159) routines to handle those assumptions.

So if I generate yml with those compacted forms, this plugin will then choke with `"yaml: unmarshal errors:\n  line 79: cannot unmarshal !!seq into plugin.condition"`.

Perhaps this plugin should be using drone-yaml for its data types?

I guess one workaround I could do is add in an exclude for a random filename that won't ever exist to make it generate the full schema.

**Comment by cmckeen** [comment]
Thanks for bringing this issue up - we'll be investigating to see how this can be fixed.

**Comment by bradrydzewski** [comment]
need to run `drone jsonnet --format=false`, otherwise when Drone formats the yaml it ignores unknown fields.

**Comment by jimsheldon** [comment]
I will close this since there appears to be a workaround. We will look into changing the yaml library to be closer to drone itself, but drone has since moved away from drone-yaml.
