### ISSUE TITLE
Consider contributing diff parsing to drone/go-scm?

### ISSUE THREAD

**Issue by donny-dont** [meltwater/drone-convert-pathschanged#34]
Drone uses [go-scm](https://github.com/drone/go-scm) to interact with the different providers but doesn't have anything around getting diffs. Maybe now that the pathschanged plugin has been around for a bit you all could consider adding to `go-scm`?

**Comment by jimsheldon** [comment]
Hello @donny-dont, are you suggesting the logic we have for querying github (and now bitbucket) for files changed in commit ranges could potentially be added to `go-scm`?

**Comment by donny-dont** [comment]
Yea it would fit with the goal of the `go-scm` library and I could see other Drone related stuff finding it useful. Brad is the ultimate decider of course but I don't think it would be very contentious to add it.

**Comment by jimsheldon** [comment]
@donny-dont from https://github.com/drone/go-scm/issues/80 it seems drone/go-scm might have this capability already.  We will investigate this soon.

**Comment by jimsheldon** [comment]
The `ListChanges` and `CompareChanges` functions from [go-scm](https://github.com/drone/go-scm) are better than what we had written, and we have since switched to use them for every supported provider. I will close this out.
