### ISSUE TITLE
Make include implicit and is optional

### ISSUE THREAD

**Issue by quantonganh** [meltwater/drone-convert-pathschanged#37]
Built-in conditions can work without a `include`: https://docs.drone.io/pipeline/docker/syntax/conditions/

Problem: `drone jsonnet --stream` auto remove `include` if there is no `exclude`: https://github.com/drone/drone-yaml/blob/master/yaml/pretty/pipeline.go#L161

it caused this conversion extension does not work as expected.

As a temporary, I have to remove [this](https://github.com/drone/drone-yaml/blob/master/yaml/pretty/pipeline.go#L161-L165) part of code to make it work.

I will try to create a PR to fix it.

**Comment by jimsheldon** [comment]
@quantonganh this looks great! Thanks so much for the contribution.

We will review this asap.
