### ISSUE TITLE
Pipeline fails to run when no files are included in commit

### ISSUE THREAD

**Issue by jmcelwain** [meltwater/drone-convert-pathschanged#45]
### Describe the bug

When there are no files included in a commit with only an exclude trigger on the pipeline, [the convert plugin will exclude the pipeline by default](https://github.com/meltwater/drone-convert-pathschanged/blob/master/plugin/parse.go#L95).

This is a bit weird, and was discovered because of faulty drone bitbucket server integration not sending the "before" commit on the webhook, meaning merge commits always showed no files changed. But, could be an issue if someone pushes a commit created with `--allow-empty`.

This may be a bit of an edge case, but I thought I'd bring it up as it was a bit hard to track down why the pipeline wasn't running.

### Steps to reproduce

1. Include a paths exclude trigger on your pipeline.
2. Push a commit with no files.

### Expected behavior

The pipeline should run, since none of the files didn't match (can't exclude nothing).

**Comment by jimsheldon** [comment]
Hello @jmcelwain, thanks for catching this!  We will work on a fix as soon as possible.

**Comment by jmcelwain** [comment]
Thanks! This project is immensely helpful to us.

**Comment by jimsheldon** [comment]
@jmcelwain #46 should fix this, if you want to review.

I think this would have also been a problem for steps, so I fixed both and added tests.

**Comment by jimsheldon** [comment]
I have released [v0.4.0](https://github.com/meltwater/drone-convert-pathschanged/releases/tag/v0.4.0) wit this fix.  I'll close this for now, if you still see issues on the new version we can open this back up.
