### ISSUE TITLE
Feature request: take --env-file parameter

### ISSUE THREAD

**Issue by jimsheldon** [meltwater/drone-convert-pathschanged#48]
### Feature

This would be essentially the same as how `drone-server` takes `--env-file=<path>` to set environment variables.

More discussion in #41

**Comment by abdennour** [comment]
any plan to release this helm chart?

**Comment by jimsheldon** [comment]
Hello @abdennour 

This change would be to just the plugin, if we end up working on a helm chart that would have to support this feature (if we implement it). It looks like you are already following #49 where we are considering helm chart support.
