### ISSUE TITLE
Feature request: Configuration for use with gitea

### ISSUE THREAD

**Issue by Halfwalker** [meltwater/drone-convert-pathschanged#52]
There are configs for github and bitbucket.  How about gitea ?  What exactly would be required ?

**Comment by moay** [comment]
I'd also need the gitea provider. Sadly, my go is nothing close to write anything like this. Setup looks simple to me, there already is a gitea provider in drone. I'd highly appreciate any effort in this.

**Comment by jimsheldon** [comment]
Hello! Thanks for the interest in this project.

Our team currently only has a use case for Github, we have no plans to add support for other providers. 

A contributor added Bitbucket Server support in #29, we would be happy to consider a pull request adding Gitea support if you would like to send us one.

I will close this for now.

Thanks again
