### ISSUE TITLE
Feature Request - Support bitbucket cloud

### ISSUE THREAD

**Issue by abdennour** [meltwater/drone-convert-pathschanged#58]
as per the [README.md](../blob/master/README.md) documentation, i can see only 2 examples :
- Github
- Bitbucket Server

Are you going to support Bitbucket Cloud ?

**Comment by jimsheldon** [comment]
Hello @abdennour 

Bitbucket Server support was added in #29 by a contributor.  Our team only has a use case for Github, so we do not have any plans to add support for other providers.

We would be happy to add support for Bitbucket Cloud through a submitted pull request if you want to add it yourself.

I will close this for now, thanks for the interest in this project!
