### ISSUE TITLE
Support multiple Conversion Extensions?

### ISSUE THREAD

**Issue by jasonchuang** [meltwater/drone-convert-pathschanged#61]
Thanks for this great conversion extension with drone!!
And according to the guide, it seems we need to config DRONE_CONVERT_PLUGIN_ENDPOINT to include this conversion plugin, but since we've already define DRONE_CONVERT_PLUGIN_ENDPOINT for our internal use,
is there any possible method to support both conversion extension together?

Thanks

**Comment by apoorva-marisomaradhya** [comment]
Hi! 
With the way drone handles conversion plugins at the moment, you will be able to enable only one conversion plugin. There's a PR open https://github.com/drone/drone/pull/2994 which would allow us to enable multiple conversion plugins, but until then we won't be able to make use of pathschanged plugin with having another conversion plugin enabled.

**Comment by jasonchuang** [comment]
Thanks for your quick comment
