### ISSUE TITLE
Feature request: Github Server

### ISSUE THREAD

**Issue by nesth** [meltwater/drone-convert-pathschanged#71]
We're currently using Github Server and this extension would be extremely useful.

**Comment by jimsheldon** [comment]
Thanks for the contribution!

I have to assume github and github server have similar (if not identical) APIs, I will see if we can rely on the same tests.

**Comment by jimsheldon** [comment]
I have published (v0.6.0](https://github.com/meltwater/drone-convert-pathschanged/releases/tag/v0.6.0) with this feature. Please give it a try and let us know if you find any issues.
