### ISSUE TITLE
Support multiple .drone.yml files

### ISSUE THREAD

**Issue by dotdiego** [meltwater/drone-convert-pathschanged#91]
Hello,

Is it a planned feature to support merging multiple drone.yml files ?
It would ensure better readability of the pipelines and provide more flexibility for mono-repos.

Thanks

**Comment by hikerspath** [comment]
Support for multiple `.drone.yml` files or a directory of yaml files is something that would have to be implemented at drone-core level.  This plugin merely takes handed off yaml from drone server, examines the path statements and returns adjusted yaml for runtime.
